## (c) HaJuegosくん- 2021 - Do not modify or impersonate the creator of this code without first asking for authorization, you may be sanctioned.
execute @s[tag=!totem] ~ ~ ~ tellraw @a {"rawtext":[{"selector":"@s"},{"text":" ha conseguido el logro:"},{"text":"§a [Postmortal]§r"}]}
tag @s add totem
execute @a ~ ~ ~ playsound random.totem @a[tag=!totem] ~ ~ ~
scoreboard players random @s totem 0 100
clear @s totem 0 1
execute @s[scores={totem=0}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 0 =! 97)"}]}
execute @s[scores={totem=1}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 1 =! 97)"}]}
execute @s[scores={totem=2}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 2 =! 97)"}]}
execute @s[scores={totem=3}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 3 =! 97)"}]}
execute @s[scores={totem=4}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 4 =! 97)"}]}
execute @s[scores={totem=5}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 5 =! 97)"}]}
execute @s[scores={totem=6}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 6 =! 97)"}]}
execute @s[scores={totem=7}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 7 =! 97)"}]}
execute @s[scores={totem=8}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 8 =! 97)"}]}
execute @s[scores={totem=9}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 9 =! 97)"}]}
execute @s[scores={totem=10}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 10 =! 97)"}]}
execute @s[scores={totem=11}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 11 =! 97)"}]}
execute @s[scores={totem=12}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 12 =! 97)"}]}
execute @s[scores={totem=13}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 13 =! 97)"}]}
execute @s[scores={totem=14}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 14 =! 97)"}]}
execute @s[scores={totem=15}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 15 =! 97)"}]}
execute @s[scores={totem=16}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 16 =! 97)"}]}
execute @s[scores={totem=17}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 17 =! 97)"}]}
execute @s[scores={totem=18}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 18 =! 97)"}]}
execute @s[scores={totem=19}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 19 =! 97)"}]}
execute @s[scores={totem=20}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 20 =! 97)"}]}
execute @s[scores={totem=21}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 21 =! 97)"}]}
execute @s[scores={totem=22}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 22 =! 97)"}]}
execute @s[scores={totem=23}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 23 =! 97)"}]}
execute @s[scores={totem=24}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 24 =! 97)"}]}
execute @s[scores={totem=25}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 25 =! 97)"}]}
execute @s[scores={totem=26}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 26 =! 97)"}]}
execute @s[scores={totem=27}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 27 =! 97)"}]}
execute @s[scores={totem=28}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 28 =! 97)"}]}
execute @s[scores={totem=29}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 29 =! 97)"}]}
execute @s[scores={totem=30}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 30 =! 97)"}]}
execute @s[scores={totem=31}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 31 =! 97)"}]}
execute @s[scores={totem=32}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 32 =! 97)"}]}
execute @s[scores={totem=33}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 33 =! 97)"}]}
execute @s[scores={totem=34}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 34 =! 97)"}]}
execute @s[scores={totem=35}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 35 =! 97)"}]}
execute @s[scores={totem=36}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 36 =! 97)"}]}
execute @s[scores={totem=37}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 37 =! 97)"}]}
execute @s[scores={totem=38}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 38 =! 97)"}]}
execute @s[scores={totem=39}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 39 =! 97)"}]}
execute @s[scores={totem=40}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 40 =! 97)"}]}
execute @s[scores={totem=41}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 41 =! 97)"}]}
execute @s[scores={totem=42}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 42 =! 97)"}]}
execute @s[scores={totem=43}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 43 =! 97)"}]}
execute @s[scores={totem=44}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 44 =! 97)"}]}
execute @s[scores={totem=45}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 45 =! 97)"}]}
execute @s[scores={totem=46}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 46 =! 97)"}]}
execute @s[scores={totem=47}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 47 =! 97)"}]}
execute @s[scores={totem=48}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 48 =! 97)"}]}
execute @s[scores={totem=49}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 49 =! 97)"}]}
execute @s[scores={totem=50}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 50 =! 97)"}]}
execute @s[scores={totem=51}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 51 =! 97)"}]}
execute @s[scores={totem=52}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 52 =! 97)"}]}
execute @s[scores={totem=53}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 53 =! 97)"}]}
execute @s[scores={totem=54}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 54 =! 97)"}]}
execute @s[scores={totem=55}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 55 =! 97)"}]}
execute @s[scores={totem=56}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 56 =! 97)"}]}
execute @s[scores={totem=57}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 57 =! 97)"}]}
execute @s[scores={totem=58}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 58 =! 97)"}]}
execute @s[scores={totem=59}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 59 =! 97)"}]}
execute @s[scores={totem=60}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 60 =! 97)"}]}
execute @s[scores={totem=61}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 61 =! 97)"}]}
execute @s[scores={totem=62}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 62 =! 97)"}]}
execute @s[scores={totem=63}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 63 =! 97)"}]}
execute @s[scores={totem=64}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 64 =! 97)"}]}
execute @s[scores={totem=65}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 65 =! 97)"}]}
execute @s[scores={totem=66}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 66 =! 97)"}]}
execute @s[scores={totem=67}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 67 =! 97)"}]}
execute @s[scores={totem=68}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 68 =! 97)"}]}
execute @s[scores={totem=69}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 69 =! 97)"}]}
execute @s[scores={totem=70}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 70 =! 97)"}]}
execute @s[scores={totem=71}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 71 =! 97)"}]}
execute @s[scores={totem=72}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 72 =! 97)"}]}
execute @s[scores={totem=73}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 73 =! 97)"}]}
execute @s[scores={totem=74}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 74 =! 97)"}]}
execute @s[scores={totem=75}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 75 =! 97)"}]}
execute @s[scores={totem=76}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 76 =! 97)"}]}
execute @s[scores={totem=77}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 77 =! 97)"}]}
execute @s[scores={totem=78}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 78 =! 97)"}]}
execute @s[scores={totem=79}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 79 =! 97)"}]}
execute @s[scores={totem=80}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 80 =! 97)"}]}
execute @s[scores={totem=81}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 81 =! 97)"}]}
execute @s[scores={totem=82}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 82 =! 97)"}]}
execute @s[scores={totem=83}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 83 =! 97)"}]}
execute @s[scores={totem=84}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 84 =! 97)"}]}
execute @s[scores={totem=85}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 85 =! 97)"}]}
execute @s[scores={totem=86}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 86 =! 97)"}]}
execute @s[scores={totem=87}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 87 =! 97)"}]}
execute @s[scores={totem=88}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 88 =! 97)"}]}
execute @s[scores={totem=89}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 89 =! 97)"}]}
execute @s[scores={totem=90}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 90 =! 97)"}]}
execute @s[scores={totem=91}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 91 =! 97)"}]}
execute @s[scores={totem=92}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 92 =! 97)"}]}
execute @s[scores={totem=93}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 93 =! 97)"}]}
execute @s[scores={totem=94}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 94 =! 97)"}]}
execute @s[scores={totem=95}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 95 =! 97)"}]}
execute @s[scores={totem=96}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 96 =! 97)"}]}
execute @s[scores={totem=97}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 97 == 97)"}]}
execute @s[scores={totem=98}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 97 == 97)"}]}
execute @s[scores={totem=99}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 97 == 97)"}]}
execute @s[scores={totem=100}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido dos totems (Probabilidad 97 == 97)"}]}