## (c) HaJuegosくん- 2021 - Do not modify or impersonate the creator of this code without first asking for authorization, you may be sanctioned.
scoreboard objectives add totem dummy totem
execute @s[tag=!totem] ~ ~ ~ tellraw @a {"rawtext":[{"selector":"@s"},{"text":" ha conseguido el logro:"},{"text":"§a [Postmortal]§r"}]}
tag @s add totem
execute @a ~ ~ ~ playsound random.totem @a[tag=!totem] ~ ~ ~
scoreboard players random @s totem 0 100
execute @s[scores={totem=0}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 0 =! 99)"}]}
execute @s[scores={totem=1}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 1 =! 99)"}]}
execute @s[scores={totem=2}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 2 =! 99)"}]}
execute @s[scores={totem=3}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 3 =! 99)"}]}
execute @s[scores={totem=4}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 4 =! 99)"}]}
execute @s[scores={totem=5}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 5 =! 99)"}]}
execute @s[scores={totem=6}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 6 =! 99)"}]}
execute @s[scores={totem=7}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 7 =! 99)"}]}
execute @s[scores={totem=8}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 8 =! 99)"}]}
execute @s[scores={totem=9}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 9 =! 99)"}]}
execute @s[scores={totem=10}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 10 =! 99)"}]}
execute @s[scores={totem=11}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 11 =! 99)"}]}
execute @s[scores={totem=12}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 12 =! 99)"}]}
execute @s[scores={totem=13}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 13 =! 99)"}]}
execute @s[scores={totem=14}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 14 =! 99)"}]}
execute @s[scores={totem=15}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 15 =! 99)"}]}
execute @s[scores={totem=16}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 16 =! 99)"}]}
execute @s[scores={totem=17}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 17 =! 99)"}]}
execute @s[scores={totem=18}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 18 =! 99)"}]}
execute @s[scores={totem=19}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 19 =! 99)"}]}
execute @s[scores={totem=20}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 20 =! 99)"}]}
execute @s[scores={totem=21}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 21 =! 99)"}]}
execute @s[scores={totem=22}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 22 =! 99)"}]}
execute @s[scores={totem=23}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 23=! 99)"}]}
execute @s[scores={totem=24}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 24 =! 99)"}]}
execute @s[scores={totem=25}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 25 =! 99)"}]}
execute @s[scores={totem=26}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 26 =! 99)"}]}
execute @s[scores={totem=27}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 27 =! 99)"}]}
execute @s[scores={totem=28}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 28 =! 99)"}]}
execute @s[scores={totem=29}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 29 =! 99)"}]}
execute @s[scores={totem=30}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 30 =! 99)"}]}
execute @s[scores={totem=31}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 31 =! 99)"}]}
execute @s[scores={totem=32}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 32 =! 99)"}]}
execute @s[scores={totem=33}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 33 =! 99)"}]}
execute @s[scores={totem=34}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 34 =! 99)"}]}
execute @s[scores={totem=35}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 35 =! 99)"}]}
execute @s[scores={totem=36}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 36 =! 99)"}]}
execute @s[scores={totem=37}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 37 =! 99)"}]}
execute @s[scores={totem=38}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 38 =! 99)"}]}
execute @s[scores={totem=39}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 39 =! 99)"}]}
execute @s[scores={totem=40}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 40 =! 99)"}]}
execute @s[scores={totem=41}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 41 =! 99)"}]}
execute @s[scores={totem=42}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 42 =! 99)"}]}
execute @s[scores={totem=43}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 43 =! 99)"}]}
execute @s[scores={totem=44}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 44 =! 99)"}]}
execute @s[scores={totem=45}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 45 =! 99)"}]}
execute @s[scores={totem=46}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 46 =! 99)"}]}
execute @s[scores={totem=47}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 47 =! 99)"}]}
execute @s[scores={totem=48}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 48 =! 99)"}]}
execute @s[scores={totem=49}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 49 =! 99)"}]}
execute @s[scores={totem=50}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 50 =! 99)"}]}
execute @s[scores={totem=51}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 51 =! 99)"}]}
execute @s[scores={totem=52}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 52 =! 99)"}]}
execute @s[scores={totem=53}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 53 =! 99)"}]}
execute @s[scores={totem=54}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 54 =! 99)"}]}
execute @s[scores={totem=55}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 55 =! 99)"}]}
execute @s[scores={totem=56}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 56 =! 99)"}]}
execute @s[scores={totem=57}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 57 =! 99)"}]}
execute @s[scores={totem=58}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 58 =! 99)"}]}
execute @s[scores={totem=59}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 59 =! 99)"}]}
execute @s[scores={totem=60}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 60 =! 99)"}]}
execute @s[scores={totem=61}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 61 =! 99)"}]}
execute @s[scores={totem=62}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 62 =! 99)"}]}
execute @s[scores={totem=63}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 63 =! 99)"}]}
execute @s[scores={totem=64}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 64 =! 99)"}]}
execute @s[scores={totem=65}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 65 =! 99)"}]}
execute @s[scores={totem=66}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 66 =! 99)"}]}
execute @s[scores={totem=67}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 67 =! 99)"}]}
execute @s[scores={totem=68}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 68 =! 99)"}]}
execute @s[scores={totem=69}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 69 =! 99)"}]}
execute @s[scores={totem=70}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 70 =! 99)"}]}
execute @s[scores={totem=71}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 71 =! 99)"}]}
execute @s[scores={totem=72}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 72 =! 99)"}]}
execute @s[scores={totem=73}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 73 =! 99)"}]}
execute @s[scores={totem=74}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 74 =! 99)"}]}
execute @s[scores={totem=75}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 75 =! 99)"}]}
execute @s[scores={totem=76}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 76 =! 99)"}]}
execute @s[scores={totem=77}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 77 =! 99)"}]}
execute @s[scores={totem=78}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 78 =! 99)"}]}
execute @s[scores={totem=79}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 79 =! 99)"}]}
execute @s[scores={totem=80}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 80 =! 99)"}]}
execute @s[scores={totem=81}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 81 =! 99)"}]}
execute @s[scores={totem=82}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 82 =! 99)"}]}
execute @s[scores={totem=83}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 83 =! 99)"}]}
execute @s[scores={totem=84}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 84 =! 99)"}]}
execute @s[scores={totem=85}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 85 =! 99)"}]}
execute @s[scores={totem=86}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 86 =! 99)"}]}
execute @s[scores={totem=87}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 87 =! 99)"}]}
execute @s[scores={totem=88}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 88 =! 99)"}]}
execute @s[scores={totem=89}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 89 =! 99)"}]}
execute @s[scores={totem=90}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 90 =! 99)"}]}
execute @s[scores={totem=91}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 91 =! 99)"}]}
execute @s[scores={totem=92}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 92 =! 99)"}]}
execute @s[scores={totem=93}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 93 =! 99)"}]}
execute @s[scores={totem=94}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 94 =! 99)"}]}
execute @s[scores={totem=95}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 95 =! 99)"}]}
execute @s[scores={totem=96}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 96 =! 99)"}]}
execute @s[scores={totem=97}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 97 =! 99)"}]}
execute @s[scores={totem=98}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 98 =! 99)"}]}
execute @s[scores={totem=99}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 99 == 99)"}]}
execute @s[scores={totem=100}] ~ ~ ~ tellraw @a {"rawtext":[{"text":"§7"},{"selector":"@s"},{"text":" ha consumido un totem (Probabilidad 99 == 99)"}]}